# This file created by conda-build 2.0.10+8.gccef906
# meta.yaml template originally from:
# /home/ilan/anaconda/packages/pytest, last modified Wed Dec  7 10:13:43 2016
# ------------------------------------------------

package:
    name: pytest
    version: 3.0.5
source:
    fn: pytest-3.0.5.tar.gz
    md5: cefd527b59332688bf5db4a10aa8a7cb
    url: https://pypi.python.org/packages/a8/87/b7ca49efe52d2b4169f2bfc49aa5e384173c4619ea8e635f123a0dac5b75/pytest-3.0.5.tar.gz
build:
    entry_points:
        - pytest = pytest:main
        - py.test = pytest:main
requirements:
    build:
        - python
        - setuptools
        - py
    run:
        - python
        - setuptools
        - py >=1.4.29
test:
    commands:
        - pytest -h
        - py.test -h
    imports:
        - pytest
about:
    description: 'The pytest framework makes it easy to write small tests, yet scales
        to

        support complex functional testing for applications and libraries.

        '
    dev_url: https://github.com/pytest-dev/pytest/
    doc_url: http://pytest.org/latest/contents.html#toc
    home: http://pytest.org/
    license: MIT
    license_file: LICENSE
    summary: Simple and powerful testing with Python
